name: timeago_flutter
description: Timeago Widget.
version: 0.1.0
author:
homepage:

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  timeago:
    path: ../timeago
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
